.PHONY: clean All

All:
	@echo "----------Building project:[ R2R - Debug ]----------"
	@cd "R2R" && "$(MAKE)" -f  "R2R.mk"
clean:
	@echo "----------Cleaning project:[ R2R - Debug ]----------"
	@cd "R2R" && "$(MAKE)" -f  "R2R.mk" clean
